# Port must be larger than 1023 and smaller than 65536
port: 6969

# Available languages are: 'en' (English) and 'es' (Spanish)
lang: "en"

# MongoDB Database name
db-name: "my-inventory"

# MongoDB Connection string
# db-url: ""
